### ISSUE TITLE
Question about full resolution download

### ISSUE THREAD

**Issue by jakeg20** [mewforest/google-art-downloader#1]
This is awesome! Do you think it would be possible to get it to download the images in full resolution? Some of the images on Google Art are in much higher resolution than 4k and it would be great if you could add downloading in full resolution in a future update if it isn't included already.

**Comment by kolt54321** [comment]
I'd like to second this question.

**Comment by mewforest** [comment]
Unfortunately Google Chrome has a bug with higher than 16K px resolution of screenshots - https://groups.google.com/a/chromium.org/forum/m/#!topic/headless-dev/DqaAEXyzvR0/discussion 

So I can't download full resolution of images, 16K px - maximum.

**Comment by kolt54321** [comment]
> Unfortunately Google Chrome has a bug with higher than 16K px resolution of screenshots - https://groups.google.com/a/chromium.org/forum/m/#!topic/headless-dev/DqaAEXyzvR0/discussion
> 
> So I can't download full resolution of images, 16K px - maximum.

Thanks for the response! Any chance of a batch downloader?

**Comment by kolt54321** [comment]
Can you switch to IEDriverServer to get around this limit?

**Comment by mewforest** [comment]
Guys, thanks to all, I can fix it with another webdriver, but the main problem still cause error: save_screenshot() can't take a screenshot of large window (50K px x 50K px).

**Comment by kolt54321** [comment]
That's fine for me... I just don't know if it's being processed correctly. Last time I tried it was something like 4k px x 4k px. 

I'll happily test it out if you create another commit with the new webdriver :) 50K res is more than enough for me.

**Comment by ciarpame** [comment]
Just found this useful tool and I second the resolution increase request. Thank you!

**Comment by lovasoa** [comment]
[GAPDecoder](https://github.com/expenses/gapdecoder/) can download the images in ultra-high resolution.
Contrarily from *google-art-downloader* it does not work by taking screenshots from a browser, so it is not subject to the limitation cited above.

**Comment by kolt54321** [comment]
> [GAPDecoder](https://github.com/expenses/gapdecoder/) can download the images in ultra-high resolution.
> Contrarily from _google-art-downloader_ it does not work by taking screenshots from a browser, so it is not subject to the limitation cited above.

I'm very impressed with the tool. Well built, well documented, and user friendly. 

I'm running into an issue with Level 7 or greater, even if the scan supports it (i.e. gigapixel scans checking via the zoom levels available). I noticed issues are disabled for your project - how could I contact you?

Edit: Anyone on 32-bit python will run into a memory error on the higher levels. Install 64-bit python instead to remove the error.

**Comment by lovasoa** [comment]
@kolt54321 : Thank you :) [Issues](https://github.com/expenses/gapdecoder/issues) are now opened on [expenses/gapdecoder](https://github.com/expenses/gapdecoder)

**Comment by mewforest** [comment]
I've updated readme, now it includes alternatives section with **gap decoder** and section about resolution limitations.

Be note: google art downloader was updated  recently, it still works as well and downloads image in resolution up to 4k.
