### ISSUE TITLE
Bug: Cropping vertical images more than 30%

### ISSUE THREAD

**Issue by neelesh93** [mewforest/google-art-downloader#10]
Thank you for your hard work
I founded a Bug: cropping vertical images 30%
@mewforest 
![Image of Bug](https://i.ibb.co/VQczDY7/bug.jpg)

**Comment by mewforest** [comment]
Did you try to mark checkbox "Check this, if your image cropped wrongly (only for elongated vertical image)"?

**Comment by mewforest** [comment]
Unfuturnately, the bug with some vertical images is still exists, it will be fixed in the next version, when I have a free time.

Thanks for a feedback!
