### ISSUE TITLE
Problem with cropping of final image

### ISSUE THREAD

**Issue by albruwa** [mewforest/google-art-downloader#11]
Hi MewForest,

This has been excellent piece of software. Thank you for creating it. I've used it to download dozens of pieces of hi-res art from Google Arts and Culture. However, suddenly, it's stopped working and I have no idea why. What I get now is the image situated at the bottom of a blank white background, occupying just a small section of that background. I have wondered whether it needs some other software to continue operating, where previously it appeared to operate independently. Here's an example of what I get.
![Anton Mauve - Flock of sheep with shepherd in the snow](https://user-images.githubusercontent.com/67813210/86503608-1ed1f400-bdf3-11ea-8e76-f89042ef7ebf.png)

**Comment by mewforest** [comment]
Thank you for your feedback! I'm appresheated to hear that 😄 

Please describe me your problem in details:
1. **What the version do you have of Google Chrome?** Chromedriver needs Google Chrome installed.
2. **Which version of the GAD are you running (compiled or source code)**?
3. **What the OS are you using?** Sometimes Chromedriver doesn't working properly on Windows 7 and older.
4. **Also, please add a hyperlink of the image to reproduce bug.**

**Comment by kolt54321** [comment]
@albruwa as a side note - what painting is that? I like it :)

**Comment by mewforest** [comment]
Please update to the latest version of google-art-downloader, the bug you described is fixed!

**UPD:** I've checked the image (Anton Mauve - Flock of sheep with shepherd in the snow) and latest version cropes the image correctly (2448px x 1162px):

![2021-11-01_00h20_28](https://user-images.githubusercontent.com/15357833/139601683-9e481b0d-abc3-4329-b30d-3157103074ee.png)

So, the issue is closed for a now.

**Comment by albruwa** [comment]
Thank you very much for updating the file. I use MalwareBytes as my
antivirus program. Are there any permissions I need to add to the
"exceptions" section of MalwareBytes? For some reason I get a stall in the
Google Downloader at the stage shown in the graphic below and it doesn't
process any further. I have included the file location in case that has
anything to do with it.

[image: Screenshot 2021-11-03 14.33.26.png]
