### ISSUE TITLE
Norton Antivirus

### ISSUE THREAD

**Issue by emresaracoglu** [mewforest/google-art-downloader#13]
Hi,

Norton Antivirus software installed on WIN 10 detects it as a threat.

![1](https://user-images.githubusercontent.com/297968/142729063-e2dde4f0-77d5-4801-8857-89ca08e7f849.png)

![resim_2021-11-20_170315](https://user-images.githubusercontent.com/297968/142729126-5e61ce5b-c655-411d-967a-fa1729b7de29.png)

Thank you.

**Comment by mewforest** [comment]
@emresaracoglu thanks for the feedback!

I'm not surprised, that Norton Antivirus is very paranoid, please check a [VirusTotal results](https://www.virustotal.com/gui/file/df43d077269909234d380b7f199294c054a69bbe12985de71b13da830a9bf23d?nocache=1) of the latest release, to ensure it is a fake detection.

By the way, all Python scripts compiled via PyInstaller will be detected as programs with low reputation, but if you want, you can [start Google Art Downloader from Python](https://github.com/mewforest/google-art-downloader#running-with-python) directly, or [compile your version](https://github.com/mewforest/google-art-downloader#compiling-to-executable).

**Comment by emresaracoglu** [comment]
I didn't mean to say there is a trojan in the project. I think you misunderstood my message. Virus protection algorithms may give different results. Of course, this does not mean 100% accuracy. I encountered such a situation during the installation and I wanted you to know about this issue.
Thanks for your repo.
cc @mewforest
