### ISSUE TITLE
Can't download any image

### ISSUE THREAD

**Issue by praneethsaichunduru** [mewforest/google-art-downloader#14]
I tried the new version, as well as 0.1.2. But both aren't working. Help me out..!

It just stuck at creating the folder "temp", after that it stays there blankly.

**Comment by mewforest** [comment]
Hello! Please download the latest Chromedriver from [here](https://chromedriver.chromium.org/downloads) and replace it in folder /bin/chromedriver_win32.

It may solves your problem.

**Comment by praneethsaichunduru** [comment]
Works like a piece of cake.

Thanks to you,
Praneeth.
