### ISSUE TITLE
[bug]No longer seems to work

### ISSUE THREAD

**Issue by MichaelKairys** [mewforest/google-art-downloader#15]
Using version 0.1.3 (compiled) with Windows 11 23H2 and Edge. 

Worked about a year ago, but when I tried it today, (1) went through 45 scraping attempts and (2) ended with "An error occurred with processing image"

Using this URL:
https://artsandculture.google.com/asset/vQEPldpJAUvS4Q

**Comment by mewforest** [comment]
@MichaelKairys It looks like the current project is completely deprecated. So I'm going to archive it. Thank you for a feedback.

Please use alternatives like https://dezoomify.ophir.dev/
