### ISSUE TITLE
Зависает на 2 шаге

### ISSUE THREAD

**Issue by kot-ezhva** [mewforest/google-art-downloader#2]
Привет!
Зависает на шаге 2, когда пытается запустить WebDriver (Scrapping: starting webdriver... [it takes several seconds]). Пробовал запускать драйвер руками (запускается на 9515 порт).
В каталоге так же создается пустая папка temp/scrapping

Версия 0.1.2 beta, Windows 10

**Comment by lovasoa** [comment]
Привет
  Кажется что код в этом repo больше не работает. Есть другие проекты которые не требуют WebDriver  и работают с текущей версии Google Arts:

 - dezoomify : https://github.com/lovasoa/dezoomify
 - dezoomify-rs: https://github.com/lovasoa/dezoomify-rs
 - gapdecoder: https://github.com/gap-decoder/gapdecoder

**Comment by kot-ezhva** [comment]
Онлайн версия - https://ophir.alwaysdata.net/dezoomify/
Проверено только что - работает!
<img width="142" alt="image" src="https://user-images.githubusercontent.com/15121885/63025831-b44e5780-beb2-11e9-80d5-b483a2af179e.png">

**Comment by mewforest** [comment]
Закрываю issue, поскольку не удалось воспроизвести проблему с Selenium. Рад, что вам помогла онлайн-версия альтернативной программы.

> Привет!
> Зависает на шаге 2, когда пытается запустить WebDriver (Scrapping: starting webdriver... [it takes several seconds]). Пробовал запускать драйвер руками (запускается на 9515 порт).
> В каталоге так же создается пустая папка temp/scrapping
> 
> Версия 0.1.2 beta, Windows 10
