### ISSUE TITLE
can not install on my computer, need help

### ISSUE THREAD

**Issue by Arnim22** [mewforest/google-art-downloader#4]
I trieded ti install but its not working

**Comment by wahengchang** [comment]
same. what is the python, pip version

**Comment by lovasoa** [comment]
I participated in several other projects that can download images from the current version of google arts & culture. You can use any of them as a replacement:

 - dezoomify : https://github.com/lovasoa/dezoomify
 - dezoomify-rs: https://github.com/lovasoa/dezoomify-rs
 - gapdecoder: https://github.com/gap-decoder/gapdecoder

**Comment by mewforest** [comment]
I've updated the project recently, so you could install dependencies from requirements.txt and follow instructions in the readme.

Also it's possible to avoid pip usage with [Poetry](https://python-poetry.org/) one-liner:

_poetry init_
