### ISSUE TITLE
Link to newer alternatives

### ISSUE THREAD

**Issue by lovasoa** [mewforest/google-art-downloader#5]
Hello @mewforest  !

Since the code in this repository does not work anymore after the google arts was updated, maybe you could point users to newer alternatives in the README ?

Among the projects that are currently working, there are:

 - dezoomify : https://github.com/lovasoa/dezoomify
 - dezoomify-rs: https://github.com/lovasoa/dezoomify-rs
 - gapdecoder: https://github.com/gap-decoder/gapdecoder

**Comment by mewforest** [comment]
Thank you for alternative links you added in pull request. I'll add them to README later.
However the latest version was based on updated Google Arts site and all works fine for me.

Please describe me your problem:
1. **What the version do you have of Google Chrome?** Chromedriver needs Google Chrome installed.
2. **Which version of the GAD are you running (compiled or source code)**?
3. **What the OS are you using?** Sometimes Chromedriver doesn't working properly on Windows 7 and older.
4. **On which step program stops?**
