### ISSUE TITLE
Doesn't download highest res

### ISSUE THREAD

**Issue by turkeyphant** [mewforest/google-art-downloader#8]
e.g. this piece: https://artsandculture.google.com/asset/sunflowers-vincent-van-gogh/XwHuufJZYFvUnA

It has a link to download at higher quality than the tool provides.

**Comment by mewforest** [comment]
I've updated readme, now it includes alternatives section and section about resolution limitations.

Be note: google art downloader was updated recently, it still works as well and downloads image in resolution up to 4k.
