### ISSUE TITLE
Enhancement: user interface

### ISSUE THREAD

**Issue by neelesh93** [mewforest/google-art-downloader#9]
For this osm project, I want to contribute by design a clean and simple user interface with google's color palette for a more cool experience (Attribution not required for my work). @mewforest 
Thank you for this tool. 
You can drop me a mail on [designer.neel@gmail.com](designer.neel@gmail.com)

**Comment by mewforest** [comment]
Thank you for suggestion, @neelesh93!

The main purpose of the google art downloader is quickest way to download images from Google Arts and Culture, so it's built on a tkinter which UI widgets are not too customizable 🙂
